name: Build and Test chx_matrix on multiple OS and architectures

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.buildplat }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-13
          - macos-14
          - windows-2022
          - windows-11-arm
        python: ["cp310", "cp311", "cp312", "cp313"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build pytest

    - name: Build package
      run: python -m build

    - name: Install built package
      run: |
        pip install dist/*.whl

    #- name: Run tests
    #  run: pytest tests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.buildplat }}-${{ matrix.python }}
        path: dist/*