name: Build and Test chx_matrix on multiple OS and architectures

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        python-version: [3.10, 3.11, 3.12, 3.13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build pytest

    - name: Build package
      run: python -m build

    - name: Install built package
      run: |
        pip install dist/*.whl

    - name: Run tests
      run: pytest tests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/*